#pragma once

enum InputCmdType
{
	INPUT_INSERT,
	INPUT_NEWLINE,
	INPUT_DELETE,
	INPUT_CURSOR_LEFT,
	INPUT_CURSOR_RIGHT,
	INPUT_CURSOR_UP,
	INPUT_CURSOR_DOWN,
	INPUT_CURSOR_HOME,
	INPUT_CURSOR_END,
	INPUT_CURSOR_DRAG,
	INPUT_CURSOR_MOVE,
	INPUT_CURSOR_PAGEUP,
	INPUT_CURSOR_PAGEDOWN,
	INPUT_CURSOR_COPY,
	INPUT_CURSOR_CUT,
	INPUT_CURSOR_PASTE
};

#define FLAG_NORMAL     (0u)
#define FLAG_HIGHLIGHT  (1u)
#define FLAG_DRAG       (2u)
#define FLAG_DELETE_FWD (0u)
#define FLAG_DELETE_BWD (1u)

struct InputCmd
{
	InputCmdType type;
	uint32_t flags;
};